name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Debug file structure
              run: |
                  echo "Current directory structure:"
                  ls -R src/

            - name: Install dependencies
              run: npm ci
              env:
                  NEXT_PUBLIC_MAPBOX: ${{ secrets.NEXT_PUBLIC_MAPBOX }}

            - name: Build
              run: npm run build
              env:
                  NEXT_PUBLIC_MAPBOX: ${{ secrets.NEXT_PUBLIC_MAPBOX }}
                  NEXT_PUBLIC_API: ${{secrets.NEXT_PUBLIC_API}}
                  NODE_ENV: production

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./out
