name: Deploy Documentation to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Install MarkBind
              run: npm install -g markbind-cli

            - name: Build documentation
              run: markbind build

            - name: Create .nojekyll file
              run: touch _site/.nojekyll

            - name: Create fix-paths script
              run: |
                  cat > fix-paths.js << 'EOL'
                  const fs = require('fs');
                  const path = require('path');

                  const baseUrl = '/AIS-Web-Portal';
                  const siteDir = path.join(__dirname, '_site');

                  function fixPaths(dir) {
                    const files = fs.readdirSync(dir);
                    
                    for (const file of files) {
                      const filePath = path.join(dir, file);
                      const stat = fs.statSync(filePath);
                      
                      if (stat.isDirectory()) {
                        fixPaths(filePath);
                      } else if (file.endsWith('.html')) {
                        let content = fs.readFileSync(filePath, 'utf8');
                        
                        // Fix script paths
                        content = content.replace(
                          /<script src="([^\/"][^"]+\.js)"><\/script>/g,
                          (match, scriptPath) => {
                            const relativePath = path.relative(siteDir, dir);
                            const newPath = relativePath ? `${baseUrl}/${relativePath}/${scriptPath}` : `${baseUrl}/${scriptPath}`;
                            return `<script src="${newPath}"></script>`;
                          }
                        );
                        
                        // Fix double slashes
                        content = content.replace(/\/AIS-Web-Portal\/\//g, '/AIS-Web-Portal/');
                        
                        // Fix dropdown menu HTML that's being displayed as text
                        // First, replace all HTML entities with their actual characters
                        content = content.replace(/&lt;/g, '<');
                        content = content.replace(/&gt;/g, '>');
                        content = content.replace(/&quot;/g, '"');
                        content = content.replace(/&amp;/g, '&');
                        
                        fs.writeFileSync(filePath, content);
                        console.log(`Fixed paths in ${filePath}`);
                      }
                    }
                  }

                  fixPaths(siteDir);
                  EOL

            - name: Fix paths
              run: node fix-paths.js

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./_site
