name: Deploy Documentation to GitHub Pages

on:
    push:
        branches:
            - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm ci

            - name: Install MarkBind
              run: npm install -g markbind-cli

            - name: Build documentation
              run: markbind build

            - name: Create .nojekyll file
              run: touch _site/.nojekyll

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./_site
